trigger:
  - main
  - develop
  - feature/*

pool: 'Docker'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'AzureStorage'
      azureResourceManagerEndpoint: 'ARM_EAGL_DEV'
      azureStorageAccountName: jdks
      azureContainerName: linuxjdks
      azureCommonVirtualFile: 'OpenJDK17U-jdk_x64_linux_hotspot_17.0.7_7.tar.gz'
      cleanDestinationDirectory: false
  - script: |
      if [ ! -d "/maven" ]; then
          echo "Download Maven"
          wget https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.1/apache-maven-3.8.1-bin.tar.gz
          echo "Unzip Maven"
          tar xzvf apache-maven-3.8.1-bin.tar.gz
          echo "Move folder"
          mv apache-maven-3.8.1 /maven
      else
          echo "Maven already downloaded"
      fi
    displayName: 'Download Maven'
  - task: Maven@3
    displayName: Test and Package
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'install'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 1.17
      jdkArchitectureOption: x64
      mavenVersionOption: Path
      mavenDirectory: '/maven'
  - script: echo "Publishing image with $(Build.BuildNumber)"

  - task: Maven@3
    displayName: Build and publish Publisher Docker Image to Container Registry
    inputs:
      mavenPomFile: 'event-dispatcher-publisher/pom.xml'
      goals: 'jib:build'
      publishJUnitResults: true
      jdkVersionOption: 1.17
      mavenVersionOption: Path
      mavenDirectory: '/maven'
      options: >
        -DskipTests=false 
        -Djib.to.image=registry.harbor.av360.org/maverick/event-dispatcher-publisher
        -Djib.to.auth.username=$(imageRegistryUsername)
        -Djib.to.auth.password=$(imageRegistryPassword)
        
