trigger:
  - main
  - develop

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      type: git
      name: A365/PipelineTemplates

steps:
  - script: echo "$(privateRegistry)"
  - task: Maven@3
    displayName: Test and Package
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'install'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 1.17
      jdkArchitectureOption: x64
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
  - script: echo "Publishing image with $(Build.BuildNumber)"
  - task: Maven@3
    displayName: Build and publish Filter Docker Image to Github Container Registry
    env:
      IMAGE_PREFIX: $(imageRegistryUrl)/maverick
      IMAGE_NAME: maverick-event-dispatcher-filter
      IMAGE_VERSION: release
      DOCKER_HOST: $(imageRegistryUrl)
      DOCKER_USER: $(docker.credentials.user)
      DOCKER_PASSWORD: $(docker.credentials.password)
    inputs:
      mavenPomFile: 'event-dispatcher-filter/pom.xml'
      goals: 'spring-boot:build-image'
      publishJUnitResults: true
      jdkVersionOption: 1.17